# Generated by Django 3.0.7 on 2022-10-18 11:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedInputDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.TextField()),
                ('device_code', models.TextField()),
                ('attached_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'attached_input_devices',
            },
        ),
        migrations.CreateModel(
            name='CaptureSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.TextField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('attached_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.AttachedInputDevice')),
            ],
            options={
                'db_table': 'capture_sessions',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InputDeviceReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.TextField()),
                ('authorization_type', models.TextField()),
                ('max_device_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'input_device_reservations',
            },
        ),
        migrations.CreateModel(
            name='SessionFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_frame', models.BinaryField()),
                ('output_frame', models.BinaryField()),
                ('frame_details', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'session_frames',
            },
        ),
        migrations.CreateModel(
            name='CaptureSessionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.TextField()),
                ('result_details', models.TextField()),
                ('capture_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.CaptureSession')),
            ],
            options={
                'db_table': 'capture_session_results',
            },
        ),
        migrations.AddField(
            model_name='attachedinputdevice',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.InputDeviceReservation'),
        ),
    ]
