# Generated by Django 3.0.7 on 2022-10-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionframe',
            name='capture_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.CaptureSession'),
            preserve_default=False,
        ),
    ]
