# Generated by Django 3.0.7 on 2022-11-04 20:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20221103_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedinputdevice',
            name='auth_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
