# Generated by Django 3.0.7 on 2022-11-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_attachedinputdevice_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturesession',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
