# Generated by Django 3.0.7 on 2022-11-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_sessionframeusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionframe',
            name='input_frame',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionframe',
            name='output_frame',
            field=models.BinaryField(null=True),
        ),
    ]
