# Generated by Django 3.0.7 on 2022-11-10 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0008_auto_20221109_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionFrameUsers',
            new_name='SessionFrameUser',
        ),
        migrations.CreateModel(
            name='CaptureSessionResultUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('capture_session_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='server.CaptureSessionResult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capture_session_result_users',
            },
        ),
    ]
