# Generated by Django 3.0.7 on 2022-11-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20221110_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionframe',
            name='input_frame',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sessionframe',
            name='output_frame',
            field=models.TextField(null=True),
        ),
    ]
